name: Build-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - main
pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: Build
  displayName: Build Completers Package
  jobs:
  - job: BuildPkg
    displayName: Build Package
    pool:
      vmImage: windows-2019
    steps:
    - pwsh: |
        $(Build.SourcesDirectory)/build.ps1 -Configuration Release
      displayName: Build

    - pwsh: |
        $env:BUILD_OUTPUT_PATH = "$(Build.SourcesDirectory)/out"
        $env:SIGNED_OUTPUT_PATH = "$(Build.SourcesDirectory)/signed"
        (Get-Item -ea ignore "$(Build.SourcesDirectory)/signed") || (New-Item -ItemType Directory -Path "$(Build.SourcesDirectory)/signed")
        Write-Verbose "BUILD_OUTPUT_PATH- $env:BUILD_OUTPUT_PATH" -Verbose
        Write-Verbose "SIGNED_OUTPUT_PATH- $env:SIGNED_OUTPUT_PATH" -Verbose
        Copy-Item "${env:BUILD_OUTPUT_PATH}/*" $env:SIGNED_OUTPUT_PATH -Recurse -Force -Verbose
      displayName: Build Signing Placeholder

    - pwsh: |
        $repoName = [guid]::newguid().ToString("N")
        $moduleName = "Microsoft.PowerShell.UnixTabCompletion"
        try {
          Register-PSRepository -Name $repoName -SourceLocation '$(System.ArtifactsDirectory)' -ErrorAction Ignore
          Publish-Module -Repository $repoName -Path "$(Build.SourcesDirectory)/signed/${moduleName}"
          $nupkg = Get-ChildItem '$(System.ArtifactsDirectory)/*.nupkg'
          $nupkgName = $nupkg.Name
          $nupkgPath = $nupkg.FullName
          Write-Host "##vso[artifact.upload containerfolder=$nupkgName;artifactname=$nupkgName;]$nupkgPath"
        }
        finally {
          Unregister-PSRepository -Name $repoName -ErrorAction SilentlyContinue
        }
        Get-ChildItem -rec '$(System.ArtifactsDirectory)' | Write-Verbose -Verbose
        Get-ChildItem -rec -file | Write-Verbose -Verbose
      displayName: Create module package


- stage: Compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: ComplianceJob
    pool:
      vmImage: Windows-latest
    steps:
    - checkout: self
    - checkout: ComplianceRepo
    - template: ci-compliance.yml@ComplianceRepo

- stage: Test
  displayName: Test Package
  jobs:
  - template: test.yml
    parameters:
      jobName: TestPkgUbuntu18
      displayName: PowerShell Core on Ubuntu 18.04
      imageName: ubuntu-latest

  - template: test.yml
    parameters:
      jobName: TestPkgWinMacOS
      displayName: PowerShell Core on macOS
      imageName: macOS-latest
