parameters:
  jobName: TestPkgWin
  imageName: windows-2019
  displayName: PowerShell Core on Windows
  powershellExecutable: pwsh

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}
  steps:
  - ${{ parameters.powershellExecutable }}: |
      Install-module Pester -Force
    displayName: Install dependencies - Pester
    timeoutInMinutes: 10

  - ${{ parameters.powershellExecutable }}: |
        Install-Module -Name "PSScriptAnalyzer" -RequiredVersion 1.20.0 -Force
    displayName: Install dependencies
    timeoutInMinutes: 10

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - ${{ parameters.powershellExecutable }}: |
      $sourceName = [guid]::newguid().ToString("N")
      $moduleName = "PSUnixCompleters"
      try {
        Register-PSRepository -Name $sourceName -SourceLocation '$(System.ArtifactsDirectory)' -ErrorAction Ignore
        Install-Module -Repository $sourceName -Name $moduleName -Scope CurrentUser
      }
      finally {
        Unregister-PSRepository -Name $sourceName -ErrorAction SilentlyContinue
      }
    displayName: Extract product artifact
    timeoutInMinutes: 10

  - ${{ parameters.powershellExecutable }}: |
      build.ps1 -test
    displayName: Execute functional tests
    errorActionPreference: continue
