parameters:
  jobName: TestPkgWin
  imageName: windows-2019
  displayName: PowerShell Core on Windows
  powershellExecutable: pwsh

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}
  steps:
  - ${{ parameters.powershellExecutable }}: |
      Install-module Pester -Force -MaximumVersion 4.99
    displayName: Install dependencies - Pester
    timeoutInMinutes: 10

  - ${{ parameters.powershellExecutable }}: |
        Install-Module -Name "PSScriptAnalyzer" -RequiredVersion 1.20.0 -Force
    displayName: Install dependencies
    timeoutInMinutes: 10

  - ${{ parameters.powershellExecutable }}: |
      Get-InstalledModule -Name pester  -AllVersions | Where-Object {$_.Version -ge ([version]::new(5,0,0))} | Uninstall-Module -Force
    displayName: Remove >= 5.0.0 Pester

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - ${{ parameters.powershellExecutable }}: |
      $sourceName = [guid]::newguid().ToString("N")
      $moduleName = "PSUnixCompleters"
      $buildOutputPath = ${}
      try {
        $null = New-Item -ItemType Directory -Path $buildOutputPath -Verbose
        Register-PSRepository -Name $sourceName -SourceLocation '$(System.ArtifactsDirectory)' -ErrorAction Ignore
        Save-Module -Repository $sourceName -Name $moduleName -Path $buildOutputPath
      }
      finally {
        Unregister-PSRepository -Name $sourceName -ErrorAction SilentlyContinue
      }
    displayName: Extract product artifact
    timeoutInMinutes: 10

  - ${{ parameters.powershellExecutable }}: |
      build.ps1 -test
    displayName: Execute functional tests
    errorActionPreference: continue
